name: Testing
version: '${project.version}'
main: com.puncher.testing.Main
api-version: 1.17
authors: [ Puncher ]
description: Minecraft Spigot Testings
website: https://github.com/Puncher1/Minecraft-Spigot

commands:
  timer:
    permission: testing.command.timer